### ISSUE TITLE
Sometimes 'Provider should be created on papiea' test fails

### ISSUE THREAD

**Issue by adolgarev** [nutanix/papiea-js#95] opened 2019-04-05 09:04 UTC
● Provider Sdk tests › Provider should be created on papiea

    Request failed with status code 500

      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:18:12)
      at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:201:11)

**Comment by shlomi-nx** [comment] 2019-04-26 16:51
@Emulebest Cannot reproduce, closing for now.

**Closed by shlomi-nx** 2019-04-26 16:51 UTC
Labels: bug, review, size: 2
